services:
  app:
    build: .
    image: impurestclub/streamcontrol:1.0.1
    container_name: streamcontrol
    env_file:
      - .env
    ports:
      - "5001:5001"  # Map port 5001 in the container to port 5001 on the host
    restart: unless-stopped
    networks:
      - streamcontrol-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
      - streamcontrol-network

  certbot:
    build: .
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./cloudflare.ini:/cloudflare.ini  # Make sure this file exists with your Cloudflare API key
    depends_on:
      - webserver
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /cloudflare.ini --email dev@wasdgaming.gg --agree-tos --no-eff-email --force-renewal -d sc.wasdgaming.gg
    networks:
      - streamcontrol-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/wasd-admin/Documents/docker/streamcontrol
      o: bind

networks:
  streamcontrol-network:
    driver: bridge
