services:
  app:
    build: .
    image: impurestclub/streamcontrol:1.0.1
    container_name: streamcontrol
    env_file:
      - path: .env
        required: true
    ports:
      - "5001:5001"  # Map port 5001 in the container to port 5001 on the host
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/live/wasdgaming.gg:/etc/letsencrypt/live/wasdgaming.gg:ro
    user: "root"