services:
  app:
    build: .
    image: impurestclub/streamcontrol:1.0.1
    env_file:
      - path: .env
        required: true
    ports:
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/live/wasdgaming.gg:/etc/letsencrypt/live/wasdgaming.gg:ro
    user: "root"
    command: ["/bin/sh", "-c", "find / -type d"]
