version: '3'  # Updated version
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "5001:5001"  # Map port 5001 in the container to port 5001 on the host
    restart: unless-stopped