services:
  app:
    build: .
    image: impurestclub/streamcontrol:1.0.1
    env_file:
      - path: .env
        required: true
    ports:
      - "5001:5001"  # Map port 5001 in the container to port 5001 on the host
    restart: unless-stopped
    volumes:
      - ./certs/origin.pem:/etc/ssl/certs/origin.pem
      - ./certs/private.key:/etc/ssl/private/private.key