# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;

    server_name sc.wasdgaming.gg;

    # Redirect all HTTP requests to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }

    # Location for Let's Encrypt challenge
    location ~ /.well-known/acme-challenge {
        root /var/www/html;
    }
}

# HTTPS Server
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name sc.wasdgaming.gg;

    # SSL Certificate and Key
    ssl_certificate /etc/letsencrypt/live/wasdgaming.gg/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wasdgaming.gg/privkey.pem;
    
    # Optional: Enable strong SSL protocols and ciphers
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384';
    ssl_prefer_server_ciphers on;

    # Document root
    root /var/www/html;
    index index.html index.htm;

    # Proxy settings for your app
    location / {
        proxy_pass http://streamcontrol:5001;  # Use container name and port as specified in docker-compose.yml
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
